services:
  candy-mysql:
    platform: linux/x86_64
    image: mysql
    container_name: candy-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./config/:/docker-entrypoint-initdb.d/
    ports:
      - 3307:3306

  candy-redis:
    image: redis
    container_name: candy-redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379