services:
  candy-mysql:
    platform: linux/x86_64
    image: mysql
    container_name: candy-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./config/:/docker-entrypoint-initdb.d/
    ports:
      - 3307:3306

  candy-redis:
    image: redis
    container_name: candy-redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379

  candy-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: candy-elasticsearch
    environment:
      - xpack.security.enabled=false
      - node.name=single-node
      - cluster.name=es-singlenode-c
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
